name = "cicd"
type = "webpack"
account_id = "9b47beba2f167662ac16b81572ee529d"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "../app/dist", entry-point = "../worker"}
compatibility_date = "2021-12-10"
kv_namespaces = [
    { binding = "VIDEOS", id = "275790a40a91474d8fea361c8d7820cd", preview_id="c226d6768e4f4670b55c5edd0ff04f4b" }
]
[vars]
CF_EMAIL="lightanson@protonmail.com"
CF_GLOBAL_API="9e71cdc773da780e5059efe41ee0887d86b08"
ACCOUNT_ID="9b47beba2f167662ac16b81572ee529d"
WHITE_LIST="cf-worker.gtc-lightanson.workers.dev,127.0.0.1,localhost"