name = "<WORKER_NAME>"
type = "webpack"
account_id = "<CLOUDFLARE_ACCOUNT_ID>"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "../app/dist", entry-point = "../worker"}
compatibility_date = "2021-12-10"
kv_namespaces = [
    {binding='',id=''}
]
[vars]
CF_EMAIL="<CLOUDFLARE_EMAIL>"
CF_API_KEY="<CLOUDFLARE_GLOBAL_API>"
ACCOUNT_ID="<CLOUDFLARE_ACCOUNT_ID>"
WHITE_LIST="<CLOUDFLARE_WHITE_LIST>"