name: Build & Deploy to Cloudflare worker

on:
  push:
    branches:
      - cicd
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      # - run: cd app && yarn install && yarn prepare && cd ..
      - run: cd worker && ls && pwd
      - run: yarn install
      - run: mv /home/runner/work/lit-cloudflare-frontend/lit-cloudflare-frontend/worker/wrangler.toml /home/runner/.wrangler/config/default.toml
      - run: CF_EMAIL=lightanson@protonmail.com CF_API_KEY=9e71cdc773da780e5059efe41ee0887d86b08 yarn wrangler publish
        env:
          CI: true
      # - name: Publish
      #   uses: cloudflare/wrangler-action@1.3.0
      #   with:
      #     apiKey: ${{ secrets.CF_GLOBAL_API }}
      #     email: ${{ secrets.CF_EMAIL }}
      #     workingDirectory: worker
      #     wranglerVersion: '1.13.0'
      #   env:
      #     CF_ACCOUNT_ID: 9b47beba2f167662ac16b81572ee529d
