name: Build & Deploy to Cloudflare worker

on:
  push:
    branches:
      - cicd
  repository_dispatch:

env:
  CF_EMAIL: ${{ secrets.CF_EMAIL }}
  CF_GLOBAL_API: ${{ secrets.CF_GLOBAL_API }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:

      # -- Rebase to root and setup to use yarn
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      # -- Build the front-end app
      - name: Build App
        working-directory: ./app
        run: yarn install && yarn prepare && ls && cd ..

      # -- Build the CloudFlare worker
      - name: Build Worker
        working-directory: ./worker
        run: yarn install && CF_EMAIL=$CF_EMAIL CF_API_KEY=$CF_GLOBAL_API yarn wrangler publish
        env:
          CI: true
